<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\Apartment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ApartmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $apartmentsData = [
            [
                'name'          => 'Cozy Studio Apartment',
                'slug' => Str::slug('Cozy Studio Apartment'),
                'rooms'         => 1,
                'beds'          => 1,
                'bathrooms'     => 1,
                'square_meters' => 35,
                'is_available'  => true,
                'is_sponsored'  => true,
                'user_id'       => 1,
            ],
            [
                'name'          => 'Spacious 2-Bedroom Apartment',
                'slug' => Str::slug('Spacious 2-Bedroom Apartment'),
                'rooms'         => 3,
                'beds'          => 2,
                'bathrooms'     => 2,
                'square_meters' => 85,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 1,
            ],
            [
                'name'          => 'Luxury Penthouse Suite',
                'slug' => Str::slug('Luxury Penthouse Suite'),
                'rooms'         => 4,
                'beds'          => 3,
                'bathrooms'     => 3,
                'square_meters' => 180,
                'is_available'  => true,
                'is_sponsored'  => true,
                'user_id'       => 1,
            ],
            [
                'name'          => 'Charming Garden Apartment',
                'slug' => Str::slug('Charming Garden Apartment'),
                'rooms'         => 2,
                'beds'          => 1,
                'bathrooms'     => 1,
                'square_meters' => 55,
                'is_available'  => false,
                'is_sponsored'  => false,
                'user_id'       => 5,
            ],
            [
                'name'          => 'Seaside Beach House',
                'slug' => Str::slug('Seaside Beach House'),
                'rooms'         => 5,
                'beds'          => 4,
                'bathrooms'     => 3,
                'square_meters' => 200,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 5,
            ],
            [
                'name'          => 'Mountain View Cabin',
                'slug' => Str::slug('Mountain View Cabin'),
                'rooms'         => 3,
                'beds'          => 2,
                'bathrooms'     => 2,
                'square_meters' => 120,
                'is_available'  => true,
                'is_sponsored'  => true,
                'user_id'       => 5,
            ],
            [
                'name'          => 'Downtown Loft Apartment',
                'slug' => Str::slug('Downtown Loft Apartment'),
                'rooms'         => 1,
                'beds'          => 1,
                'bathrooms'     => 1,
                'square_meters' => 40,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 7,
            ],
            [
                'name'          => 'Rural Farmhouse Retreat',
                'slug' => Str::slug('Rural Farmhouse Retreat'),
                'rooms'         => 4,
                'beds'          => 3,
                'bathrooms'     => 2,
                'square_meters' => 150,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 7,
            ],
            [
                'name'          => 'Sunny Beachfront Condo',
                'slug' => Str::slug('Sunny Beachfront Condo'),
                'rooms'         => 2,
                'beds'          => 1,
                'bathrooms'     => 1,
                'square_meters' => 60,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 7,
            ],
            [
                'name'          => 'Historic City Center Apartment',
                'slug' => Str::slug('Historic City Center Apartment'),
                'rooms'         => 2,
                'beds'          => 1,
                'bathrooms'     => 1,
                'square_meters' => 65,
                'is_available'  => false,
                'is_sponsored'  => false,
                'user_id'       => 4,
            ],
            [
                'name'          => 'Riverside Cabin Retreat',
                'slug' => Str::slug('Riverside Cabin Retreat'),
                'rooms'         => 3,
                'beds'          => 2,
                'bathrooms'     => 1,
                'square_meters' => 80,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 4,
            ],
            [
                'name'          => 'Urban Studio Loft',
                'slug' => Str::slug('Urban Studio Loft'),
                'rooms'         => 1,
                'beds'          => 1,
                'bathrooms'     => 1,
                'square_meters' => 45,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 4,
            ],
            [
                'name'          => 'Secluded Lakeside Cottage',
                'slug' => Str::slug('Secluded Lakeside Cottage'),
                'rooms'         => 2,
                'beds'          => 1,
                'bathrooms'     => 1,
                'square_meters' => 70,
                'is_available'  => false,
                'is_sponsored'  => false,
                'user_id'       => 19,
            ],
            [
                'name'          => 'Mountain Retreat Chalet',
                'slug' => Str::slug('Mountain Retreat Chalet'),
                'rooms'         => 3,
                'beds'          => 2,
                'bathrooms'     => 2,
                'square_meters' => 100,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 19,
            ],
            [
                'name'          => 'Downtown Luxury Penthouse',
                'slug' => Str::slug('Downtown Luxury Penthouse'),
                'rooms'         => 4,
                'beds'          => 3,
                'bathrooms'     => 3,
                'square_meters' => 180,
                'is_available'  => true,
                'is_sponsored'  => false,
                'user_id'       => 19,
            ],
            [
                'name'          => 'City View Apartment',
                'slug' => Str::slug('City View Apartment'),
                'rooms'         => 2,
                'beds'          => 2,
                'bathrooms'     => 2,
                'square_meters' => 75,
                'is_available'  => false,
                'is_sponsored'  => false,
                'user_id'       => 15,
            ],
            [
                'name'          => 'Countryside Villa',
                'slug' => Str::slug('Countryside Villa'),
                'rooms'         => 5,
                'beds'          => 4,
                'bathrooms'     => 3,
                'square_meters' => 220,
                'is_available'  => true,
                'is_sponsored'  => true,
                'user_id'       => 15,
            ],
            [
                'name'          => 'Oceanfront Paradise',
                'slug' => Str::slug('Oceanfront Paradise'),
                'rooms'         => 3,
                'beds'          => 2,
                'bathrooms'     => 2,
                'square_meters' => 120,
                'is_available'  => true,
                'is_sponsored'  => true,
                'user_id'       => 15,
            ],
            [
                'name' => 'Downtown Loft',
                'slug' => Str::slug('Downtown Loft'),
                'rooms' => 2,
                'beds' => 1,
                'bathrooms' => 1,
                'square_meters' => 60,
                'is_available' => true,
                'is_sponsored' => false,
                'user_id' => 8,
            ],
            [
                'name' => 'Riverside Cabin',
                'slug' => Str::slug('Riverside Cabin'),
                'rooms' => 2,
                'beds' => 1,
                'bathrooms' => 1,
                'square_meters' => 70,
                'is_available' => false,
                'is_sponsored' => false,
                'user_id' => 8,
            ],
            [
                'name' => 'Mountain View Chalet',
                'slug' => Str::slug('Mountain View Chalet'),
                'rooms' => 3,
                'beds' => 2,
                'bathrooms' => 2,
                'square_meters' => 100,
                'is_available' => true,
                'is_sponsored' => false,
                'user_id' => 8,
            ],
            [
                'name' => 'Beachfront Bungalow',
                'slug' => Str::slug('Beachfront Bungalow'),
                'rooms' => 2,
                'beds' => 1,
                'bathrooms' => 1,
                'square_meters' => 65,
                'is_available' => true,
                'is_sponsored' => false,
                'user_id' => 8,
            ],
            [
                'name' => 'Mountain Retreat Cabin',
                'slug' => Str::slug('Mountain Retreat Cabin'),
                'rooms' => 2,
                'beds' => 1,
                'bathrooms' => 1,
                'square_meters' => 75,
                'is_available' => false,
                'is_sponsored' => false,
                'user_id' => 11,
            ],
            [
                'name' => 'Lakeside Cottage',
                'slug' => Str::slug('Lakeside Cottage'),
                'rooms' => 3,
                'beds' => 2,
                'bathrooms' => 2,
                'square_meters' => 100,
                'is_available' => true,
                'is_sponsored' => false,
                'user_id' => 11,
            ],
            [
                'name' => 'Luxury Villa with Pool',
                'slug' => Str::slug('Luxury Villa with Pool'),
                'rooms' => 6,
                'beds' => 4,
                'bathrooms' => 5,
                'square_meters' => 350,
                'is_available' => true,
                'is_sponsored' => false,
                'user_id' => 1,
            ],
            [
                'name' => 'Downtown Studio Apartment',
                'slug' => Str::slug('Downtown Studio Apartment'),
                'rooms' => 1,
                'beds' => 1,
                'bathrooms' => 1,
                'square_meters' => 40,
                'is_available' => true,
                'is_sponsored' => false,
                'user_id' => 11,
            ],
            [
                'name' => 'Forest Retreat Cabin',
                'slug' => Str::slug('Forest Retreat Cabin'),
                'rooms' => 2,
                'beds' => 1,
                'bathrooms' => 1,
                'square_meters' => 60,
                'is_available' => false,
                'is_sponsored' => true,
                'user_id' => 11,
            ],
            [
                'name' => 'Seaside Apartment with a View',
                'slug' => Str::slug('Seaside Apartment with a View'),
                'rooms' => 2,
                'beds' => 1,
                'bathrooms' => 1,
                'square_meters' => 65,
                'is_available' => false,
                'is_sponsored' => false,
                'user_id' => 16,
            ],
            [
                'name' => 'Rustic Mountain Cabin',
                'slug' => Str::slug('Rustic Mountain Cabin'),
                'rooms' => 3,
                'beds' => 2,
                'bathrooms' => 2,
                'square_meters' => 80,
                'is_available' => true,
                'is_sponsored' => false,
                'user_id' => 16,
            ],
            [
                'name' => 'Beachfront Paradise Villa',
                'slug' => Str::slug('Beachfront Paradise Villa'),
                'rooms' => 4,
                'beds' => 3,
                'bathrooms' => 3,
                'square_meters' => 220,
                'is_available' => true,
                'is_sponsored' => true,
                'user_id' => 16,
            ],
        ];

        foreach ($apartmentsData as $apartmentData) {
            Apartment::create([
                'name'          => $apartmentData['name'],
                'slug'          => $apartmentData['slug'],
                'rooms'         => $apartmentData['rooms'],
                'beds'          => $apartmentData['beds'],
                'bathrooms'     => $apartmentData['bathrooms'],
                'square_meters' => $apartmentData['square_meters'],
                'is_available'  => $apartmentData['is_available'],
                'is_sponsored'  => $apartmentData['is_sponsored'],
                'user_id'       => $apartmentData['user_id'],
            ]);
        }

        // foreach (Apartment::all() as $apartmentData) {
        //     $apartmentData->services()->attach(
        //         Service::inRandomOrder()->take(rand(1, 3))->pluck('id')->toArray()
        //     );

        //     $apartmentData->services()->sync($apartmentData['services']);
        // }

        // $apartment->sponsorships()->sync($apartmentData['sponsorships']);

        foreach (Apartment::all() as $apartmentFromDb) {
            $randomServices = Service::inRandomOrder()->take(rand(1, 3))->pluck('id')->toArray();
            $apartmentFromDb->services()->attach($randomServices);
        }
    }
};




